---

language: python

python:
  - 2.7

env:
  global:
    - DJANGO_CONF="conf.travis"

install:
  - pip install -r www/deploy/requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python -m flake8 .
  - python www/manage.py syncdb --noinput
  - cd www && python ./manage.py test --noinput

services:
  - postgresql

notifications:
  email:
    on_success: change
    on_failure: always
